### ISSUE TITLE
Days 58-60 Twitter

### ISSUE THREAD

**Issue by CodeitchNY** [talkpython/100daysofcode-with-python-course#41]
Might need to update the md or video for this set of days.

apps.twitter.com is being sunsetted and moved to https://developer.twitter.com/en/apps

There is also an approval process (maybe there always was, but there is one now)

**Comment by CodeitchNY** [comment]
LOL. and they are being a bit of a PITA about it. I blame the Russians....

**Comment by bbelderbos** [comment]
Thanks @CodeitchNY, I can update the README. 

Were you able to create your app without too much hassle? 

I just create another one and it got approved instantly, but that might be because I had 2 approved apps on my account already. 

I hope this is not a blocker. If so, another option could be to provide a static copy of the data set.

Cheers, 
Bob

**Comment by CodeitchNY** [comment]
There was a little bit of back and forth with them. Could have been I got the new guy, even though I claimed to student, educational purposes, no commercial or marketing needs. And that their own automation terms said, use it to learn and try new stuff (4-5 emails. All very polite). The last email was me saying, I don't get it, I will move on to another service to explore. And then I got approved. Go figure.
